# Generated by Django 5.2.15 on 2026-07-06 12:12

from django.db import migrations, models


def mark_existing_profiles_complete(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.exclude(display_name="").exclude(display_name__isnull=True).update(
        profile_setup_complete=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_profiles_complete, migrations.RunPython.noop),
    ]
