# Generated by Django 5.2.15 on 2026-06-24 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusview',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.status'),
        ),
        migrations.AddField(
            model_name='statusview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['user', 'expires_at'], name='stories_sta_user_id_aa4aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['expires_at'], name='stories_sta_expires_43153e_idx'),
        ),
        migrations.AddIndex(
            model_name='statusview',
            index=models.Index(fields=['status', 'viewer'], name='stories_sta_status__b66ab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statusview',
            unique_together={('status', 'viewer')},
        ),
    ]
