# Generated by Django 5.2.15 on 2026-07-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_322420_idx',
            old_name='chat_messag_convers_del_idx',
        ),
    ]
