# Generated by Django 5.2.15 on 2026-07-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_reaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='chat_messag_message_ce4293_idx',
            old_name='chat_messag_message_emoji_idx',
        ),
    ]
