# Generated by Django 5.2.15 on 2026-07-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_hidden'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagehidden',
            new_name='chat_messag_user_id_bcc8db_idx',
            old_name='chat_messag_user_msg_hid_idx',
        ),
    ]
