# Generated by Django 5.2.15 on 2026-07-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_conversation_favourite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationfavourite',
            new_name='chat_conver_user_id_306296_idx',
            old_name='chat_fav_user_created_idx',
        ),
    ]
