# Generated by Django 5.2.15 on 2026-07-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_conversation_archive_block'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationarchive',
            new_name='chat_conver_user_id_9041a5_idx',
            old_name='chat_arch_user_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationblock',
            new_name='chat_conver_user_id_3b24bb_idx',
            old_name='chat_block_user_block_idx',
        ),
    ]
