# Generated by Django 5.2.17 on 2026-09-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversation_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='conversationpin',
            new_name='chat_conver_user_id_2a9c98_idx',
            old_name='chat_pin_user_pinned_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, help_text='Original message this one was forwarded from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message this one quotes (inline reply).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagedraft',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='messagedraft',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Quoted message kept with the draft.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagedraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagedraft',
            index=models.Index(fields=['user', '-updated_at'], name='chat_messag_user_id_4f90da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagedraft',
            unique_together={('conversation', 'user')},
        ),
    ]
