# Generated by Django 5.2.15 on 2026-09-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_disappearing_view_once_presence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_expires_06e82e_idx',
            old_name='chat_messag_expires_3f8a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_b998ca_idx',
            old_name='chat_messag_convers_9a1b4d_idx',
        ),
    ]
